### ISSUE TITLE
Home page has lots of bug

### ISSUE THREAD

**Issue by sheetalj2205** [Vishal-raj-1/Awesome-JavaScript-Projects#1224]
## Describe the bug
I want to fix the bug of the navbar, about us section for GSSOC 21.
## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by FaizAlam** [comment]
I want to work towards improving home page ui design and eliminate major bugs which makes website less visibly attractive.
Some of the bugs :
1. About us section
2. horizontal line not in the center
3. Less padding throughout the website which makes things cluttered
4. Nav bar design can be improved
(Attaching screenshots for better understanding)

I can solve this by majorly playing around with flex properties and paddings of different element.

I believe this website should reach more masses an to achieve that we'll have to make home page visually appealing.
Website should have clean nav bar and element's padding, so that website look spacious at the same time have all the necessary information.

Browser: Google Chrome
Os: Mac OS

Please assign me this issue so that i can fix the bugs asap.


<img width="1258" alt="Screenshot 2021-04-29 at 9 44 10 PM" src="https://user-images.githubusercontent.com/21370009/116605754-71b20480-a94d-11eb-80fd-fc899d159442.png">
<img width="1275" alt="Screenshot 2021-04-29 at 9 46 09 PM" src="https://user-images.githubusercontent.com/21370009/116605764-75de2200-a94d-11eb-96fb-24dbe6cdb802.png">
<img width="1269" alt="Screenshot 2021-04-29 at 9 46 16 PM" src="https://user-images.githubusercontent.com/21370009/116605768-7676b880-a94d-11eb-9fe8-a62fe695b51b.png">

**Comment by 991rajat** [comment]
Hey @sheetalj2205  and @FaizAlam Would you able to divide the work
@sheetalj2205   could work on Home Page
@FaizAlam could work on about page 
Or whatever you decide let me know, I'll assign it to you.

**Comment by sheetalj2205** [comment]
Ok! I will work on home page.

**Comment by 991rajat** [comment]
@sheetalj2205  If @FaizAlam not replied in 24Hrs You should work on issue too.

**Comment by FaizAlam** [comment]
@991rajat please check PR request#1252

**Comment by sheetalj2205** [comment]
Please assign this to me.

**Comment by 991rajat** [comment]
@sheetalj2205 Sorry I forgot to assign you. Most of things are fixed on the Page by Faizan. There are few changes required, 
I will ask @sheetalj2205  to fix that.
There are two Awesome text
Make the footer of full width.
Remove the cartoonik
![image](https://user-images.githubusercontent.com/38184186/116886649-f26f4a00-ac46-11eb-8204-ffb828b9b5ae.png)

**Comment by sheetalj2205** [comment]
> @sheetalj2205 Sorry I forgot to assign you. Most of things are fixed on the Page by Faizan. There are few changes required,
> I will ask @sheetalj2205 to fix that.
> There are two Awesome text
> Make the footer of full width.
> Remove the cartoonik
> ![image](https://user-images.githubusercontent.com/38184186/116886649-f26f4a00-ac46-11eb-8204-ffb828b9b5ae.png)

okay! I have started working on it . Please give it a level label too.

**Comment by 991rajat** [comment]
Make a PR, will label that!

**Comment by 991rajat** [comment]
@sheetalj2205 Make footer look like Contact Page.
Copy text too, That's right.

**Comment by sheetalj2205** [comment]
why I am not able to clon this repository?

**Comment by 991rajat** [comment]
@sheetalj2205 You need to fork it, And then clone. it.

**Comment by sheetalj2205** [comment]
> @sheetalj2205 You need to fork it, And then clone. it.

Please check my PR 1319
