### ISSUE TITLE
Want to add a ToDo list project.  

### ISSUE THREAD

**Issue by Anubhav7298** [Vishal-raj-1/Awesome-JavaScript-Projects#675]
I want to add a todo list project. 
This web based application uses following tech stack:
HTML, CSS, javascript, mongoose
I have used mongodb database server to store the data and heroku to host the website.

username :  Anubhav_7298 #7182

**Comment by satwik16** [comment]
hey @Anubhav7298  I would like to contribute to this project , as I am familiar to the tech stack required

**Comment by 991rajat** [comment]
Everyone rightnow this issue is under development some other participant is working on it. Once it's developed you can create new issue for modification or new features.
Feel free to look around, plenty of things can be added or modified within this project. Create an issue we will be happy to assign you.
I'm closing this issue for now
